### ISSUE TITLE
Get usage statistics on resellers without a domain name fails

### ISSUE THREAD

**Issue by n8whnp** [vbaranovskiy-plesk/whmcs-plugin#12] opened 2016-12-22 19:10 UTC
With Plesk it is possible to create resellers without a domain name, so when the getWebspacesUsage function in comes to get the usage statistics, it fails with the following in the module log:
Request:
<?xml version="1.0" encoding="UTF-8"?><packet version="1.6.4.0"><webspace>
    <get>
        <filter>
                         <name></name>
                    </filter>
        <dataset>
            <resource-usage/>
            <limits/>
            <gen_info/>
        </dataset>
    </get>
</webspace></packet>
Response:
<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.4.0"><webspace><get><result><status>error</status><errcode>1013</errcode><errtext>Domain with name '' does not exist
</errtext></result></get></webspace></packet>
Requisites:
1. A client configured in WHMCS
2. A Plesk server "
Reproduction steps:
1. Login to WHMCS admin, navigate to Setup > Products/Services > Products/Services
2. Create a Reseller Hosting product
3. Set any name, description and price.
4. UNtick the Require Domain option
5. Assign to the Plesk module and configure a plan and reseller plan name
6. Save Changes
7. Navigate to Setup > General Settings > Ordering tab and tick "Enable Random Usernames"
8. Save Changes
9. Navigate to Orders > Add New Order and place an order for the newly created product. Take care to leave the "Domain" field empty.
10. Provision the account on the server.
11. Navigate to Reports > Disk Usage Summary > Update Now
12. Assert: The usage statistics for the new Plesk reseller account are not updated.

**Comment by jas8522** [comment] 2016-12-28 01:43
Connected to this is the fact that reseller plans (with associated domains) only show usage stats for the subscription connected to the primary domain. In other words, the usage stats showing in WHMCS are completely wrong.

For example, one reseller of ours is at 88GB of 120GB storage usage, however in WHMCS it only shows 11GB of "Unlimited" because that's what the subscription associated with their 'primary' domain in WHMCS is configured to.

I'm working on modifying the plesk_UsageUpdate() hook such that it detects hosting plans of type 'reselleraccount' in WHMCS and, instead of grabbing webspace (subscription) stats for those plans, it will grab reseller account stats. Once implemented, this should resolve both of our issues with usage stats not updating properly.

**Comment by jas8522** [comment] 2017-01-18 00:27
I've now got some code in place for this that *should* work to resolve both of these issues in that it will grab reseller stats based on username for all resellers on the server that WHMCS sends to _UsageUpdate. It hasn't yet been tested. See here: https://github.com/jas8522/whmcs-plugin/tree/reseller-plan-stats-update

**Comment by jas8522** [comment] 2017-02-24 00:32
This is now confirmed tested and fixed with #19 as referenced above.

**Comment by jas8522** [comment] 2017-10-13 17:59
This can be closed now.

**Closed as completed** 2017-10-16 06:26 UTC
