### ISSUE TITLE
bug exclusive ip-address in _getFreeDedicatedIp

### ISSUE THREAD

**Issue by elnarvi** [vbaranovskiy-plesk/whmcs-plugin#20] opened 2017-03-21 16:07 UTC
The dedicated reseller IPs included them in free IPS ... Attached patch for _getFreeDedicatedIp() function

Sorry for my English... xD

**Comment by elnarvi** [comment] 2017-03-21 16:10
/lib/Plesk/Manager/V1632.php

After:

`        foreach($domains->xpath('//webspace/get/result') as $item) {
            try {
                $this->_checkErrors($item);
                foreach($item->data->hosting->vrt_hst->ip_address as $ip) {
                    $ipListUse[(string)$ip] = (string)$ip;
                }
            } catch (Exception $e) {
                if (Plesk_Api::ERROR_OBJECT_NOT_FOUND != $e->getCode()) {
                    throw $e;
                }
            }
        }`

Included:

`		$resellers = Plesk_Registry::getInstance()->api->resellers_get();	
		if(isset($resellers) && !empty($resellers)) {
			foreach($resellers->xpath('//reseller/get/result') as $item) {
				try {
					$this->_checkErrors($item);
					foreach($item->data->ippool->ip as $ip) {
						if($ip->{'ip-type'}=="exclusive") {
							$ipListUse[(string)$ip->{'ip-address'}] = (string)$ip->{'ip-address'};
						}
					}
				} catch (Exception $e) {
					if (Plesk_Api::ERROR_OBJECT_NOT_FOUND != $e->getCode()) {
						throw $e;
					}
				}
			}
		}`

/templates/api/1.6.3.2/resellers_get.tpl

`
<reseller>
    <get>
		<filter/>
        <dataset>
			<ippool/>
        </dataset>
    </get>
</reseller>`

**Comment by n8whnp** [comment] 2017-06-26 19:40
This appears to be a duplicate of #13.

**Comment by vbaranovskiy-plesk** [comment] 2020-02-25 06:52
This repository is no longer maintained. All questions regarding the WHMCS Plesk Provisioning Module should be addressed to WHMCS Technical Support. https://www.whmcs.com/submit-a-ticket/

**Closed as completed by vbaranovskiy-plesk** 2020-02-25 06:52 UTC
